version: '3.3'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ghdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data:
